/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/hand-phone.glb 
Author: Poliko (https://sketchfab.com/Poliko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hand-holding-phone-6d99aa43705c44bcadde799b9a617d1c
Title: Hand holding phone
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hand-phone.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCube2_phong2_0.geometry} material={materials.phong2} position={[2.009, 17.123, 1.184]} scale={[0.733, 5.756, 11.72]} />
      <mesh geometry={nodes.pCube19_manoparazetatratadaenzeta2aiFlat1_0.geometry} material={materials.manoparazetatratadaenzeta2aiFlat1} position={[2.14, 16.956, 1.443]} scale={[0.119, 6.231, 9.725]} />
      <mesh geometry={nodes.manoparazetatratadaenzeta2Group56172_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
      <mesh geometry={nodes.manoparazetatratadaenzeta2Group56172_aiStandardSurface2_0_1.geometry} material={materials.aiStandardSurface2} />
      <mesh geometry={nodes.manoparazetatratadaenzeta2pCube19_lambert1_0.geometry} material={materials.lambert1} position={[2.158, 16.956, 1.443]} scale={[0.119, 6.231, 9.725]} />
    </group>
  )
}

useGLTF.preload('/hand-phone.glb')
